### ISSUE TITLE
Where to put the project description?

### ISSUE THREAD

**Issue by sarkar4540** [dernasherbrezon/deb-maven-plugin#1]
The error after setting up my pom.xml is:

     Failed to execute goal com.aerse.maven:deb-maven-plugin:1.0:package (package) on project Dhoaa: project description is mandatory -> [Help 1]
     
     To see the full stack trace of the errors, re-run Maven with the -e switch.
     Re-run Maven using the -X switch to enable full debug logging.

     For more information about the errors and possible solutions, please read the following articles:
     [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

And my pom.xml configuration is:

     <plugin>
                <groupId>com.aerse.maven</groupId>
                <artifactId>deb-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <id>package</id>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <project>
                        <name>Dhoaa</name>
                        <developers>Aniruddha Sarkar&lt;sarkar4540@gmail.com&gt;</developers>
                        <description>Your music player.</description>
                    </project>
                    <unixUserId>ubuntu</unixUserId>
                    
                    <unixGroupId>ubuntu</unixGroupId>
                    <osDependencies>
                        <openjdk-8-jre></openjdk-8-jre>
                        <libvlc-dev></libvlc-dev>
                        <maven></maven>
                    </osDependencies>
                    <javaServiceWrapper>true</javaServiceWrapper>
                    <fileSets>
                        <fileSet>
                            <source>${basedir}/src/main/deb</source>
                            <target>/</target>
                        </fileSet>
                    </fileSets>
                    <attachArtifact>true</attachArtifact>
                </configuration>
            </plugin>

Where am I missing?

**Comment by dernasherbrezon** [comment]
According to the log:

> on project Dhoaa: project description is mandatory

You should setup project description for your pom.xml instead of plugin.

**Comment by sarkar4540** [comment]
Github: http://github.com/altcode-india/dhoaa

**Comment by sarkar4540** [comment]
Okay

**Comment by dernasherbrezon** [comment]
Here is an example: https://github.com/dernasherbrezon/r2cloud/blob/master/pom.xml
