### ISSUE TITLE
Warn: maintainer-script-calls-systemctl

### ISSUE THREAD

**Issue by dernasherbrezon** [dernasherbrezon/deb-maven-plugin#11]
Fix lintian warning:
https://lintian.debian.org/tags/maintainer-script-calls-systemctl.html

Replace systemctl with deb-systemd-invoke

**Comment by daviddean-x** [comment]
How this could be fixed manually?

**Comment by dernasherbrezon** [comment]
It needs to be changed in the plugin. This plugin will auto-generate some maintainer-script parts, which will generate the warning above.

**Comment by daviddean-x** [comment]
Okay I searched over all the code and there are no references of systemctl, like you said it will be generated, but didn't study all of this project so I had asked.
Thank you

**Comment by dernasherbrezon** [comment]
Ah. You're right. Can't find it either.
