### ISSUE TITLE
Installing to multiple locations

### ISSUE THREAD

**Issue by lolepezy** [dernasherbrezon/deb-maven-plugin#9]
Hi,

I am trying to use this plugin for creating a package that contains files with the layout like this:
/etc/rpki-validator.conf
/usr/lib/rpki-validator/app.jar
/var/lib/rpki-validator-db
/usr/bin/rpki-validator.sh

Is it possible to generate such a package? 

At the moment I am trying something like 

```
 <configuration>
                    <unixUserId>rpki</unixUserId>
                    <unixGroupId>rpki</unixGroupId>
                    <osDependencies>
                        <default-jre>>=8</default-jre>
                        <coreutils>>=8.26</coreutils>
                        <systemd></systemd>
                        <rsync></rsync>
                    </osDependencies>
                    <attachArtifact>true</attachArtifact>
                    <javaServiceWrapper>false</javaServiceWrapper>
                    <fileSets>
                        <fileSet>                            
                           <source>${basedir}/src/main/resources/packaging/deb/scripts/rpki-validator.sh</source>
                            <target>usr/bin/rpki-validator.sh</target>
                        </fileSet>
                        <fileSet>
                            <source>${basedir}/src/main/resources/packaging/deb/conf/rpki-validator.conf</source>
                            <target>etc/rpki-validator.conf</target>
                        </fileSet>
                        <fileSet>
                            <source>${basedir}/src/main/resources/packaging/generic/db</source>
                            <target>var/lib/rpki-validator-db</target>
                        </fileSet>
                     .... and so on
                    </fileSets>
                </configuration>
```

But it doesn't want to install, saying
dpkg: error processing archive ./rpki-validator-20191024160129.deb (--unpack):
 error creating directory 'home/rpki/rpki-validator//etc/systemd/system/': No such file or directory
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)

I looked at this example
https://github.com/dernasherbrezon/r2cloud/blob/master/pom.xml#L353
And I don't see much difference, except for the less detailed target paths

Can you suggest what could be the problem?

**Comment by dernasherbrezon** [comment]
Can you try "installDir" option. Setting it to "/" should do the trick. Another option would be manual copying the file from "/home/user/app/etc/" to "/etc". The latter is not a recommended "debian way".
